name: Deploy Line-chatbot

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: bestbest/line-chatbot:${{ github.sha }}

    - name: Deploy via SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
        echo '#!/usr/bin/expect -f' > deploy_expect.sh
        echo 'set timeout -1' >> deploy_expect.sh
        echo 'exp_internal 1' >> deploy_expect.sh
        echo 'spawn ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p 3022 4504@gate.manage.proen.cloud' >> deploy_expect.sh
        echo 'expect "Enter \[0-5\]:" { send "3\r" }' >> deploy_expect.sh
        echo 'expect "Enter \[0-2\]:" { send "2\r" }' >> deploy_expect.sh
        echo 'expect "root@*" { send "docker pull bestbest/line-chatbot:${{ github.sha }}\r" }' >> deploy_expect.sh
        echo 'expect "root@*" { send "docker stop optimistic_haslett && docker rm optimistic_haslett\r" }' >> deploy_expect.sh
        echo 'expect "root@*" { send "docker run -d --name optimistic_haslett -p 6789:6789 bestbest/line-chatbot:${{ github.sha }}\r" }' >> deploy_expect.sh
        echo 'expect "root@*" { send "exit\r" }' >> deploy_expect.sh
        echo 'expect eof' >> deploy_expect.sh
        chmod +x deploy_expect.sh
        ./deploy_expect.sh
